version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix(deps)"
      prefix-development: "fix(deps)"
    assignees:
      - "sample-app-developers"
      - "sample-app-technical-leads"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix(deps)"
      prefix-development: "fix(deps)"
    assignees:
      - "sample-app-developers"
      - "sample-app-technical-leads"